export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const UPDATE_FIELD_MESSAGE = 'UPDATE_FIELD_MESSAGE';
export const CLEAR_FIELD_MESSAGE = 'CLEAR_FIELD_MESSAGE';